### ISSUE TITLE
"Access Denied" when adding pull request to asana task

### ISSUE THREAD

**Issue by cogerk** [Asana/comment-on-task-github-action#28]
Hi All,

After following the steps here: https://github.com/Asana/comment-on-task-github-action 

I am getting an "access denied" in Asana as shown below:

<img width="663" alt="Image" src="https://github.com/user-attachments/assets/d61c4c35-5d48-4a39-a680-b43a63c0d5c9" />

Summary of what I did: 
1. generate secret token: https://github.integrations.asana.plus/auth?domainId=ghactions. 
2. set up secret as ASANA_SECRET in my organization's private repo
3. add following new .yaml file in .github/workflows directory of the repo:
```
# this enables asana tasks to be linked to pull requests
# copied from: https://github.com/marketplace/actions/attach-pull-request-to-asana-task
on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-asana-attachment-job:
    runs-on: ubuntu-latest
    name: Create pull request attachments on Asana tasks
    steps:
      - name: Create pull request attachments
        uses: Asana/create-app-attachment-github-action@latest
        id: postAttachment
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
      - name: Log output status
        run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
```
4.  commit/push/merge new yaml file to main
5. add/authenticate github app to asana project 

what am I missing? is there a way to see a log and see what if this yml file is throwing an error?
